// Swedish error copy. Codes match the exceptions raised by the SQL RPCs
// (supabase/migrations/*_rpc_*.sql) plus client-side network/config errors.

export const ERROR_MESSAGES = {
  // Guest
  player_not_found: 'Vi hittar inte ditt konto. Det kan ha raderats av spelledaren.',
  invalid_token: 'Din inloggning gäller inte längre.',
  name_empty: 'Skriv ett namn först.',
  name_too_long: 'Namnet är för långt (max 24 tecken).',
  race_not_found: 'Loppet finns inte.',
  race_not_betting: 'Spelet är stängt för det här loppet.',
  horse_not_found: 'Hästen finns inte i det här loppet.',
  stake_too_low: 'Minsta insats är 10 RM.',
  stake_too_high: 'Max 250 RM per kula. Brädet tål inte mer.',
  insufficient_balance: 'Du har inte råd med den insatsen. Snabblån finns, tyvärr.',
  loan_not_allowed: 'Du har fortfarande pengar kvar. Spela upp dem först.',
  bad_amount: 'Välj ett belopp först.',
  no_debt: 'Du är skuldfri. Njut medan det varar.',
  repay_too_large: 'Beloppet är större än din skuld eller ditt saldo. Försök igen.',
  item_not_found: 'Varan finns inte längre i butiken.',
  item_inactive: 'Varan är tillfälligt ur sortimentet.',
  out_of_stock: 'Slutsålt. Någon var snabbare än du.',
  coupon_not_found: 'Vi hittar ingen kupong med den koden. Kontrollera koden och försök igen.',
  coupon_used: 'Kupongen är redan inlöst. En kupong gäller en gång.',
  card_not_found: 'Det där vinstkortet känner vi inte igen. Det kan ha fått en ny kod.',
  card_inactive: 'Vinstkortet är pausat av spelledaren. Fråga den som höll i leken.',
  card_cooldown: 'Lugn i stallet. Vänta några sekunder innan du skannar igen.',
  // Game master
  gm_unauthorized: 'Fel lösenord.',
  gm_no_password: 'Inget spelledarlösenord är satt i databasen.',
  invalid_field: 'Fältet är ogiltigt.',
  race_in_progress: 'Avsluta eller stryk pågående lopp först.',
  race_not_paddock: 'Fältet kan bara slumpas om i paddocken.',
  race_not_running: 'Loppet pågår inte.',
  invalid_transition: 'Det steget går inte just nu.',
  invalid_order: 'Resultatordningen är ogiltig.',
  invalid_ruling: 'Okänt domslut.',
  balance_negative: 'Saldot kan inte bli negativt.',
  bad_run_ms: 'Ogiltig looptid.',
  kusk_not_found: 'Kusken finns inte.',
  bad_price: 'Priset måste vara noll eller mer.',
  bad_stock: 'Lagret måste vara noll eller mer, eller tomt för obegränsat.',
  bad_kind: 'Okänd varutyp.',
  bad_effect: 'Okänd effekt.',
  purchase_not_found: 'Köpet finns inte.',
  bad_tier: 'Okänd kupongvalör.',
  bad_count: 'Antalet kuponger måste vara mellan 1 och 200.',
  coupon_amount: 'Kupongvärdet måste vara mellan 1 och 5 000 RM.',
  coupon_code_failed: 'Kunde inte skapa unika koder. Försök igen.',
  coupon_batch_not_found: 'Kupongomgången finns inte.',
  coupon_not_redeemed: 'Kupongen är inte inlöst.',
  bad_card_tier: 'Okänd valör för vinstkortet.',
  card_code_failed: 'Kunde inte skapa en unik kod. Försök igen.',
  prize_claim_not_found: 'Utbetalningen finns inte längre.',
  // Client side
  network: 'Ingen anslutning. Försöker igen...',
  config: 'Mr Green saknar serverinställningar.',
  unknown: 'Något gick fel. Försök igen.',
} as const

export type ErrorCode = keyof typeof ERROR_MESSAGES
