// Swedish copy for the game master app (src/gm): login, race control, live bets, players, kuskar.

export const GM_LOGIN = {
  title: "Spelledare",
  subtitle: "Bara för Simon.",
  passwordLabel: "Lösenord",
  submit: "Logga in",
  empty: "Skriv lösenordet först.",
  remembered: "Lösenordet sparas på den här iPaden.",
} as const;

export const GM_TABS = {
  race: "Lopp",
  bets: "Spel",
  players: "Spelare",
  shop: "Butik",
  kuskar: "Kuskar",
  toAttract: "Attract",
  open: "Spelledare",
  logout: "Logga ut",
} as const;

export const GM_RACE = {
  noActive: "Inget aktivt lopp.",
  noActiveHint: "Skapa ett lopp för att öppna paddocken.",
  loading: "Hämtar loppet",
  create: "Skapa lopp",
  reroll: "Slumpa om",
  openBetting: "Öppna spel",
  closeBetting: "Stäng spelet",
  reopenBetting: "Öppna igen",
  start: "Starta loppet",
  void: "Stryk loppet",
  voidConfirmTitle: "Stryk loppet?",
  voidConfirmText:
    "Alla öppna spel betalas tillbaka till spelarna. Det går inte att ångra.",
  voidConfirmOk: "Ja, stryk loppet",
  cancel: "Avbryt",
  next: "Nästa lopp",
  skip: "Snabbspola",
  publish: "Publicera resultat",
  clock: (m: string) => `${m} m`,
  // Display race screen staging.
  stretchBanner: "Upploppet!",
  photoStamp: "Målfoto",
  winnerStamp: "Vinnare",
  skrall: "Skräll!",
  atStake: (rm: string) => `${rm} står på spel`,
  noBackers: "Ingen har pengar här. Än.",
  backers: (pool: string) => `${pool}:`,
  moreBackers: (n: number) => `+${n}`,
  /** The chip on a horse stuck in a server crash. */
  notFound: "404",
  /** The penalty chip on a kusk who opened the hjälprebus. */
  penalty: "+5 min",
  /** The shot nobody answers, on a kusk playing sänka skepp alone. */
  miss: "E5?",
  gag: {
    galopp: "Galopp!",
    snabblan: "Snabblån!",
    husvagn: "Husvagnspanik!",
    kommitte: "Kommitté-incest!",
    serverkrasch: "Serverkrasch!",
    fatbyte: "Fatbyte!",
    eckero: "Eckerölinjen!",
    rallyhafte: "Glömde rallyhäftet!",
    hjalprebus: "Hjälprebus!",
    frossa: "Frossa!",
    vaniljsas: "Vaniljsås!",
    sankaskepp: "Sänka skepp!",
    olvisvep: "Olvisvep!",
    goblin: "Goblin mode!",
    snostorm: "Snöstorm!",
    gulsno: "Äter gul snö!",
    artsoppa: "Ärtsoppa!",
    chicane: "Chicane!",
    vaxlaupp: "Växla upp!",
  },
  pot: "Total pott",
  bets: (n: number) => (n === 1 ? "1 spel" : `${n} spel`),
  resultTitle: (raceNo: number) => `Lopp ${raceNo}, resultat`,
  voidedTitle: (raceNo: number) => `Lopp ${raceNo} ströks`,
  voidedText: "Öppna spel betalades tillbaka.",
  place: (i: number) => `${i}:a`,
  ruling: {
    none: "Godkänt utan anmärkning.",
    pay_new_winner: "Ny vinnare efter utredning.",
    void: "Loppet ströks efter utredning. Huset behöll insatserna.",
    dismiss: "Utredningen lades ner. Resultatet står fast.",
  },
  winners: "Vinnare",
  noWinners: "Ingen hade rätt. Huset tackar.",
  houseNet: "Husets netto",
  inquiryWait: "Domarna tittar på videon...",
  // Control phone, while the race runs on the iPad.
  liveTitle: "Loppet pågår",
  leader: "Leder",
  /** The held start: the display counts the field down, so the phone says why nothing moves. */
  phaseCountdown: (n: number) => `Startar om ${n}`,
  phaseGo: "Och de är iväg",
  phaseRunning: "Loppet rullar",
  phaseFinishing: "I mål, väntar",
  phaseDone: "Publicerar resultat",
  publishing: "Skickar resultatet...",
  publishFailed: "Resultatet gick inte ut. Försök igen.",
  onDisplay: "Visas på skärmen just nu",
  rulePayNewWinner: "Betala ny vinnare",
  ruleVoid: "Stryk, huset behåller insatserna",
  ruleDismiss: "Ogilla, resultatet står fast",
} as const;

export const GM_BETS = {
  noRace: "Inget aktivt lopp att visa spel för.",
  empty: "Inga spel ännu. Huset väntar tålmodigt.",
  pot: "Total pott",
  count: (n: number) => (n === 1 ? "1 spel" : `${n} spel`),
  ifWins: "Om hästen vinner, huset",
  feed: "Senaste spel",
  unknownPlayer: "Okänd spelare",
} as const;

export const GM_PLINKO = {
  title: "Plånko idag",
  empty: "Ingen har släppt en kula än.",
  drops: "Kulor",
  staked: "Insatt",
  paid: "Utbetalt",
  house: "Huset",
  best: "Största träff",
} as const;

export const GM_PLAYERS = {
  title: "Spelare",
  count: (n: number) => (n === 1 ? "1 spelare" : `${n} spelare`),
  empty: "Inga spelare än. Visa QR-koden och le.",
  balance: "Saldo",
  debt: "Skuld",
  loans: "Snabblån",
  adjustLabel: "Justera saldo",
  adjustPlaceholder: "Belopp, t.ex. 100 eller -50",
  adjustApply: "Justera",
  adjustInvalid: "Skriv ett heltal, t.ex. 100 eller -50.",
  adjusted: (label: string, rm: string) => `${label} har nu ${rm}.`,
  renameLabel: "Nytt namn",
  renameApply: "Byt namn",
  renamed: (label: string) => `Bytte namn till ${label}.`,
  deleteConfirmTitle: (label: string) => `Radera ${label}?`,
  deleteConfirmText:
    "Spelaren och alla spelarens spel försvinner. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (label: string) => `${label} är raderad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  close: "Klar",
  reset: "Nollställ dagen",
  resetConfirmTitle: "Nollställ hela dagen?",
  resetConfirmText:
    "Alla spelare, spel och lopp raderas. Kuskar och lösenord finns kvar. Gäster måste registrera sig igen. Det går inte att ångra.",
  resetConfirmOk: "Ja, nollställ allt",
  resetDone: "Dagen är nollställd.",
} as const;

/** The control phone's preview of the guests' pop-up offers (nothing is sent to the guests). */
export const GM_OFFERS = {
  title: "Förhandsvisa erbjudanden",
  hint: "Bara på den här telefonen. Tryck på ett erbjudande för att se det som gästerna ser det.",
  random: "Slumpa ett",
} as const;

export const GM_SHOP = {
  title: "Butik",
  hint: "Svarta marknaden. Priser och lager gäller direkt på alla telefoner.",
  new: "Ny vara",
  active: "I hyllan",
  inactive: "Ur sortimentet",
  digital: "Digital",
  stock: (n: number) => (n === 1 ? "1 kvar" : `${n} kvar`),
  unlimited: "Obegränsat",
  soldOut: "Slutsålt",
  addStock: "+1",
  markSoldOut: "Slut",
  nameLabel: "Namn",
  blurbLabel: "Beskrivning",
  priceLabel: "Pris i RM",
  stockLabel: "Lager",
  stockHint: "Lämna tomt för obegränsat. Noll betyder slutsålt.",
  stockError: "Skriv ett tal eller lämna tomt.",
  priceError: "Skriv ett pris, noll eller mer.",
  sortLabel: "Ordning",
  activeLabel: "Syns i butiken",
  save: "Spara",
  saved: (name: string) => `${name} är sparad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  deleteConfirmTitle: (name: string) => `Radera ${name}?`,
  deleteConfirmText:
    "Varan försvinner ur butiken. Gamla kvitton står kvar. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (name: string) => `${name} är raderad.`,
  empty: "Inga varor än. Lägg upp det som faktiskt står i kylen.",
  soldTitle: "Sålt idag",
  soldHint: "Nyast först. Ej hämtad betyder att gästen inte har tryckt på Hämta än.",
  soldEmpty: "Ingen har handlat än.",
  soldTotal: (rm: string) => `${rm} omsatt`,
  refund: "Ångra",
  refundConfirmTitle: (name: string) => `Ångra ${name}?`,
  refundConfirmText:
    "Pengarna går tillbaka, varan hamnar i hyllan (eller vinsten i lådan) igen och kvittot försvinner.",
  refundConfirmOk: "Ja, ångra köpet",
  refunded: (name: string) => `${name} är återbetald.`,
  bar: "Bar",
  box: "Mystery Box",
  marker: "Marker",
  markerReceipt: (n: number) => `Marker × ${n}`,
  markerClaimed: "Hämtad",
  markerUnclaimed: "Ej hämtad",
  boxLeft: (n: number) => (n === 1 ? "1 kvar i lådan" : `${n} kvar i lådan`),
  imageLabel: "Bild",
  imageHint: "Filnamn i public/butik/, till exempel ol.jpg. Tomt ger en paketruta.",
  fromBox: (prize: string) => `Mystery Box: ${prize}`,
  prizesTitle: "Lådans innehåll",
  prizesHint: "Fysiska vinster. En vinst lämnar lådan när någon får den. Chansen gäller nästa öppning.",
  newPrize: "Ny vinst",
  prizesEmpty: "Lådan är tom. Lägg i något, annars går den inte att öppna.",
  rarityLabel: "Sällsynthet",
  countLabel: "Antal i lådan",
  countError: "Skriv ett antal, noll eller mer.",
  prizeDeleteConfirmTitle: (name: string) => `Ta ut ${name} ur lådan?`,
  prizeDeleteConfirmText: "Vinsten försvinner ur lådan. Gamla kvitton står kvar. Det går inte att ångra.",
} as const;

export const GM_KUSKAR = {
  title: "Kuskar",
  hint: "Tre av fyra kuskar lottas ur listan, alltid minst en ur stallet. Den fjärde slumpas fram.",
  new: "Ny kusk",
  active: "Aktiv",
  inactive: "Inaktiv",
  notesCount: (n: number) => (n === 1 ? "1 kommentar" : `${n} kommentarer`),
  nameLabel: "Namn",
  notesLabel: "Kommentarer, en per rad",
  notesHint: (n: number) => `${n} av 7. Håll alla på samma tema.`,
  activeLabel: "Med i fältgenereringen",
  save: "Spara",
  saved: (name: string) => `${name} är sparad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  deleteConfirmTitle: (name: string) => `Radera ${name}?`,
  deleteConfirmText:
    "Kusken försvinner ur fältgenereringen. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (name: string) => `${name} är raderad.`,
  empty: "Inga kuskar än.",
} as const;

export const GM_COUPONS = {
  title: "Kuponger",
  subtitle:
    "Skriv ut kuponger som gästerna skannar när de vinner något i den fysiska världen. En kupong gäller en gång.",
  createTitle: "Skapa kuponger",
  tierLabel: "Valör",
  countLabel: "Antal",
  countHint: "Hur många kuponger i den här omgången. Max 200.",
  countError: "Skriv ett tal mellan 1 och 200.",
  labelLabel: "Etikett",
  labelHint:
    "Vilken lek kupongen tillhör, till exempel Dart. Trycks på kupongen och syns i flödet.",
  baseLabel: "Adress i QR-koden",
  baseHint: "Måste vara adressen gästernas telefoner kan nå.",
  baseWarning:
    "Det här ser ut som en testadress. Kuponger med den här adressen fungerar inte på festen.",
  create: "Skapa och visa",
  created: (n: number) => (n === 1 ? "1 kupong skapad." : `${n} kuponger skapade.`),
  sheetTitle: "Utskrift",
  sheetHint:
    "Tolv kuponger per A4. Skriv ut, klipp längs de streckade linjerna och dela ut en per vinst.",
  print: "Skriv ut",
  sheetClose: "Stäng utskriften",
  batchesTitle: "Omgångar",
  batchesEmpty: "Inga kuponger skapade än.",
  batchCount: (total: number, redeemed: number) =>
    `${total} st, ${redeemed} inlösta`,
  batchLeft: (n: number) => (n === 1 ? "1 kvar" : `${n} kvar`),
  batchNoLabel: "Utan etikett",
  /** The bonuskupong prank: printed value on the chip, the real payout next to it. */
  batchPays: (rm: string) => `betalar ut ${rm}`,
  reprint: "Skriv ut igen",
  deleteBatch: "Radera",
  cancel: "Avbryt",
  deleteConfirmTitle: "Radera omgången?",
  deleteConfirmText:
    "Alla kuponger i omgången slutar gälla, även de som redan är utskrivna och utdelade. Inlösta pengar ligger kvar på kontona. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (n: number) =>
    n === 1 ? "1 kupong raderad." : `${n} kuponger raderade.`,
  claimsTitle: "Inlösta idag",
  claimsEmpty: "Ingen har löst in en kupong än.",
  undo: "Ångra",
  undone: (rm: string) => `${rm} draget tillbaka. Kupongen går att lösa in igen.`,
  someone: "Raderad spelare",
} as const;

/** The Vinstkort section on /gm/kuponger: reusable cards scanned inside the guest app. */
export const GM_PRIZE_CARDS = {
  title: "Vinstkort",
  subtitle:
    "Ett kort per lek som lekledaren bär på och visar för vinnaren. Kortet tar aldrig slut. Gästen skannar det i appen, en gång per fem sekunder.",
  createTitle: "Nytt vinstkort",
  tierLabel: "Valör",
  labelLabel: "Etikett",
  labelHint: "Vilken lek kortet hör till, till exempel Dart. Trycks på kortet och syns i flödet.",
  create: "Skapa och skriv ut",
  created: "Vinstkort skapat.",
  cardsTitle: "Korten",
  cardsEmpty: "Inga vinstkort än.",
  noLabel: "Utan etikett",
  claims: (n: number, rm: string) => (n === 1 ? `1 utbetalning, ${rm}` : `${n} utbetalningar, ${rm}`),
  paused: "Pausat",
  pause: "Pausa",
  resume: "Aktivera",
  pausedToast: "Kortet är pausat. Skanningar nekas tills du aktiverar det.",
  resumedToast: "Kortet är aktivt igen.",
  reprint: "Skriv ut",
  rotate: "Ny kod",
  rotateConfirmTitle: "Ge kortet en ny kod?",
  rotateConfirmText:
    "Den gamla koden slutar gälla direkt, även alla foton av den. Du måste skriva ut kortet igen och byta det utskrivna.",
  rotateConfirmOk: "Ja, ny kod",
  rotated: "Ny kod klar. Skriv ut och byt kortet.",
  delete: "Radera",
  deleteConfirmTitle: "Radera kortet?",
  deleteConfirmText:
    "Kortet slutar gälla direkt. Utbetalningar som redan gjorts ligger kvar på kontona och i flödet. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: "Vinstkortet raderat.",
  cancel: "Avbryt",
  feedTitle: "Vinstkort idag",
  feedEmpty: "Ingen har skannat ett vinstkort än.",
  /** Shown on a claim when the same guest has cashed the same card this many times tonight. */
  repeat: (n: number) => {
    const suffix = [1, 2].includes(n % 10) && ![11, 12].includes(n % 100) ? "a" : "e";
    return `${n}:${suffix} gången på det här kortet`;
  },
  undo: "Ångra",
  undone: (rm: string) => `${rm} draget tillbaka.`,
  someone: "Raderad spelare",
  sheetTitle: "Utskrift av vinstkort",
  sheetHint: "Ett kort per A4. Klipp ut, plasta gärna in, och ge det till lekledaren.",
  print: "Skriv ut",
  sheetClose: "Stäng utskriften",
} as const;

/** Dev-only race lab at /styleguide/race, for tuning the race screen without a backend. */
export const GM_RACE_LAB = {
  seed: "Seed",
  random: "Slumpa",
  replay: "Spela igen",
  pause: "Paus",
  play: "Spela",
  script: "Upplägg",
  gag: "Gag",
  upplopp: "Upploppsgag",
  inquiry: "Utredning",
  scripts: {
    wire: "Start-mål",
    comeback: "Från sist",
    collapse: "Tar slut",
    duel: "Duell",
    pack: "Klunga",
  },
} as const;
