// Swedish copy for the game master app (src/gm): login, race control, live bets, players, kuskar.

export const GM_LOGIN = {
  title: "Spelledare",
  subtitle: "Bara för Simon.",
  passwordLabel: "Lösenord",
  submit: "Logga in",
  empty: "Skriv lösenordet först.",
  remembered: "Lösenordet sparas på den här iPaden.",
} as const;

export const GM_TABS = {
  race: "Lopp",
  bets: "Spel",
  players: "Spelare",
  shop: "Butik",
  kuskar: "Kuskar",
  toAttract: "Attract",
  open: "Spelledare",
  logout: "Logga ut",
} as const;

export const GM_RACE = {
  noActive: "Inget aktivt lopp.",
  noActiveHint: "Skapa ett lopp för att öppna paddocken.",
  loading: "Hämtar loppet",
  create: "Skapa lopp",
  reroll: "Slumpa om",
  openBetting: "Öppna spel",
  closeBetting: "Stäng spelet",
  reopenBetting: "Öppna igen",
  start: "Starta loppet",
  void: "Stryk loppet",
  voidConfirmTitle: "Stryk loppet?",
  voidConfirmText:
    "Alla öppna spel betalas tillbaka till spelarna. Det går inte att ångra.",
  voidConfirmOk: "Ja, stryk loppet",
  cancel: "Avbryt",
  next: "Nästa lopp",
  skip: "Snabbspola",
  publish: "Publicera resultat",
  clock: (m: string) => `${m} m`,
  pot: "Total pott",
  bets: (n: number) => (n === 1 ? "1 spel" : `${n} spel`),
  resultTitle: (raceNo: number) => `Lopp ${raceNo}, resultat`,
  voidedTitle: (raceNo: number) => `Lopp ${raceNo} ströks`,
  voidedText: "Öppna spel betalades tillbaka.",
  place: (i: number) => `${i}:a`,
  ruling: {
    none: "Godkänt utan anmärkning.",
    pay_new_winner: "Ny vinnare efter utredning.",
    void: "Loppet ströks efter utredning. Huset behöll insatserna.",
    dismiss: "Utredningen lades ner. Resultatet står fast.",
  },
  winners: "Vinnare",
  noWinners: "Ingen hade rätt. Huset tackar.",
  houseNet: "Husets netto",
  inquiryWait: "Domarna tittar på videon...",
  // Control phone, while the race runs on the iPad.
  liveTitle: "Loppet pågår",
  leader: "Leder",
  phaseRunning: "Loppet rullar",
  phaseFinishing: "I mål, väntar",
  phaseDone: "Publicerar resultat",
  publishing: "Skickar resultatet...",
  publishFailed: "Resultatet gick inte ut. Försök igen.",
  onDisplay: "Visas på skärmen just nu",
  rulePayNewWinner: "Betala ny vinnare",
  ruleVoid: "Stryk, huset behåller insatserna",
  ruleDismiss: "Ogilla, resultatet står fast",
} as const;

export const GM_BETS = {
  noRace: "Inget aktivt lopp att visa spel för.",
  empty: "Inga spel ännu. Huset väntar tålmodigt.",
  pot: "Total pott",
  count: (n: number) => (n === 1 ? "1 spel" : `${n} spel`),
  ifWins: "Om hästen vinner, huset",
  feed: "Senaste spel",
  unknownPlayer: "Okänd spelare",
} as const;

export const GM_PLAYERS = {
  title: "Spelare",
  count: (n: number) => (n === 1 ? "1 spelare" : `${n} spelare`),
  empty: "Inga spelare än. Visa QR-koden och le.",
  balance: "Saldo",
  debt: "Skuld",
  loans: "Snabblån",
  adjustLabel: "Justera saldo",
  adjustPlaceholder: "Belopp, t.ex. 100 eller -50",
  adjustApply: "Justera",
  adjustInvalid: "Skriv ett heltal, t.ex. 100 eller -50.",
  adjusted: (label: string, rm: string) => `${label} har nu ${rm}.`,
  renameLabel: "Nytt namn",
  renameApply: "Byt namn",
  renamed: (label: string) => `Bytte namn till ${label}.`,
  deleteConfirmTitle: (label: string) => `Radera ${label}?`,
  deleteConfirmText:
    "Spelaren och alla spelarens spel försvinner. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (label: string) => `${label} är raderad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  close: "Klar",
  reset: "Nollställ kvällen",
  resetConfirmTitle: "Nollställ hela kvällen?",
  resetConfirmText:
    "Alla spelare, spel och lopp raderas. Kuskar och lösenord finns kvar. Gäster måste registrera sig igen. Det går inte att ångra.",
  resetConfirmOk: "Ja, nollställ allt",
  resetDone: "Kvällen är nollställd.",
} as const;

export const GM_SHOP = {
  title: "Butik",
  hint: "Svarta marknaden. Priser och lager gäller direkt på alla telefoner.",
  new: "Ny vara",
  active: "I hyllan",
  inactive: "Ur sortimentet",
  physical: "Fysisk",
  digital: "Digital",
  stock: (n: number) => (n === 1 ? "1 kvar" : `${n} kvar`),
  unlimited: "Obegränsat",
  soldOut: "Slutsålt",
  addStock: "+1",
  markSoldOut: "Slut",
  nameLabel: "Namn",
  blurbLabel: "Beskrivning",
  priceLabel: "Pris i RM",
  stockLabel: "Lager",
  stockHint: "Lämna tomt för obegränsat. Noll betyder slutsålt.",
  stockError: "Skriv ett tal eller lämna tomt.",
  priceError: "Skriv ett pris, noll eller mer.",
  kindLabel: "Typ",
  effectLabel: "Extra",
  effectNone: "Inget",
  effectTitle: "Titel",
  effectBadge: "Emoji",
  effectValueLabel: "Titeln eller emojin",
  effectValueHint: "Syns bredvid namnet på topplistan.",
  sortLabel: "Ordning",
  activeLabel: "Syns i butiken",
  save: "Spara",
  saved: (name: string) => `${name} är sparad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  deleteConfirmTitle: (name: string) => `Radera ${name}?`,
  deleteConfirmText:
    "Varan försvinner ur butiken. Gamla kvitton står kvar. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (name: string) => `${name} är raderad.`,
  empty: "Inga varor än. Lägg upp det som faktiskt står i kylen.",
  soldTitle: "Sålt i kväll",
  soldHint: "Nyast först. Varje rad är något någon vill ha i handen.",
  soldEmpty: "Ingen har handlat än.",
  soldTotal: (rm: string) => `${rm} omsatt`,
  refund: "Ångra",
  refundConfirmTitle: (name: string) => `Ångra ${name}?`,
  refundConfirmText:
    "Pengarna går tillbaka, varan hamnar i hyllan igen och kvittot försvinner.",
  refundConfirmOk: "Ja, ångra köpet",
  refunded: (name: string) => `${name} är återbetald.`,
} as const;

export const GM_KUSKAR = {
  title: "Kuskar",
  hint: "Tre av fyra kuskar lottas ur listan, alltid minst en ur stallet. Den fjärde slumpas fram.",
  new: "Ny kusk",
  active: "Aktiv",
  inactive: "Inaktiv",
  notesCount: (n: number) => (n === 1 ? "1 kommentar" : `${n} kommentarer`),
  nameLabel: "Namn",
  notesLabel: "Kommentarer, en per rad",
  notesHint: (n: number) => `${n} av 7. Håll alla på samma tema.`,
  activeLabel: "Med i fältgenereringen",
  save: "Spara",
  saved: (name: string) => `${name} är sparad.`,
  cancel: "Avbryt",
  edit: "Redigera",
  delete: "Radera",
  deleteConfirmTitle: (name: string) => `Radera ${name}?`,
  deleteConfirmText:
    "Kusken försvinner ur fältgenereringen. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (name: string) => `${name} är raderad.`,
  empty: "Inga kuskar än.",
} as const;

export const GM_COUPONS = {
  title: "Kuponger",
  subtitle:
    "Skriv ut kuponger som gästerna skannar när de vinner något i den fysiska världen. En kupong gäller en gång.",
  createTitle: "Skapa kuponger",
  tierLabel: "Valör",
  countLabel: "Antal",
  countHint: "Hur många kuponger i den här omgången. Max 200.",
  countError: "Skriv ett tal mellan 1 och 200.",
  labelLabel: "Etikett",
  labelHint:
    "Vilken lek kupongen tillhör, till exempel Dart. Trycks på kupongen och syns i flödet.",
  baseLabel: "Adress i QR-koden",
  baseHint: "Måste vara adressen gästernas telefoner kan nå.",
  baseWarning:
    "Det här ser ut som en testadress. Kuponger med den här adressen fungerar inte på festen.",
  create: "Skapa och visa",
  created: (n: number) => (n === 1 ? "1 kupong skapad." : `${n} kuponger skapade.`),
  sheetTitle: "Utskrift",
  sheetHint:
    "Tolv kuponger per A4. Skriv ut, klipp längs de streckade linjerna och dela ut en per vinst.",
  print: "Skriv ut",
  sheetClose: "Stäng utskriften",
  batchesTitle: "Omgångar",
  batchesEmpty: "Inga kuponger skapade än.",
  batchCount: (total: number, redeemed: number) =>
    `${total} st, ${redeemed} inlösta`,
  batchLeft: (n: number) => (n === 1 ? "1 kvar" : `${n} kvar`),
  batchNoLabel: "Utan etikett",
  reprint: "Skriv ut igen",
  deleteBatch: "Radera",
  cancel: "Avbryt",
  deleteConfirmTitle: "Radera omgången?",
  deleteConfirmText:
    "Alla kuponger i omgången slutar gälla, även de som redan är utskrivna och utdelade. Inlösta pengar ligger kvar på kontona. Det går inte att ångra.",
  deleteConfirmOk: "Ja, radera",
  deleted: (n: number) =>
    n === 1 ? "1 kupong raderad." : `${n} kuponger raderade.`,
  claimsTitle: "Inlösta i kväll",
  claimsEmpty: "Ingen har löst in en kupong än.",
  undo: "Ångra",
  undone: (rm: string) => `${rm} draget tillbaka. Kupongen går att lösa in igen.`,
  someone: "Raderad spelare",
} as const;
